services:
  app:
    build:
      dockerfile: Dockerfile
    volumes:
      - .env:/app/.env
      - ./src:/app/src
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
      - ./poetry.lock:/app/poetry.lock
      - ./pyproject.toml:/app/pyproject.toml
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
  
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST: ${POSTGRES__POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES__POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES__POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES__POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES__POSTGRES_PASS}
    env_file:
      - .env
  
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    environment:
      - REDIS_PASSWORD=${REDIS__REDIS_PASSWORD}
      - REDIS_PORT=${REDIS__REDIS_PORT}
      - REDIS_DATABASES=${REDIS__REDIS_DATABASES}