"""comment.score column

Revision ID: fd8994b2f31e
Revises: d76acc07cbdb
Create Date: 2025-07-26 12:14:28.561381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd8994b2f31e'
down_revision: Union[str, Sequence[str], None] = 'd76acc07cbdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('score', sa.Integer(), nullable=False))
    op.drop_column('comment', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('comment', 'score')
    # ### end Alembic commands ###
